config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cocktails do
    resources :doses, only: [:new, :create, :destroy]
  end
  delete "doses/:id", to: "doses#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_many :doses, :dependent => :destroy
  has_many :ingredients, through: :doses
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates_uniqueness_of :cocktail, :scope => :ingredient
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_many :doses
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :set_cocktail, only: [:show, :edit, :update, :destroy]

  def index
    @cocktails = Cocktail.all
  end

  def show
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @cocktail.update(cocktail_params)
    @cocktail.save
    redirect_to cocktail_path(@cocktail)
  end

  def destroy
    @cocktail.destroy
    redirect_to cocktails_path
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name)
  end

  def set_cocktail
    @cocktail = Cocktail.find(params[:id])
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  before_action :find_cocktail, only: [ :new, :create ]

  def new
    @dose = Dose.new
  end

  def create
    @dose = @cocktail.doses.build(dose_params)
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktails_path
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end

  def find_cocktail
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/_form.html.erb
<%= simple_form_for @cocktail do |f| %>
  <%= f.input :name %>
  <%= f.button :submit %>
<% end %>

app/views/cocktails/edit.html.erb
<h1>Edit Cocktail</h1>

<%= render "form" %>

app/views/cocktails/index.html.erb
<h1>All the Cocktails</h1>

<p><%= link_to "Add a new cocktail", new_cocktail_path %></p>

<ul>
  <% @cocktails.each do |cock| %>
    <li>
    <h2><%= link_to cock.name, cocktail_path(cock) %></h2>
    </li>
  <% end %>
</ul>

app/views/cocktails/new.html.erb
<h1>New Cocktail</h1>

<%= render "form" %>

app/views/cocktails/show.html.erb
<h1><%= @cocktail.name %></h1>

<h2>Dose</h2>
   <% @cocktail.doses.each do |dose| %>
   <h3> <%= dose.description %> </h3>
   <h4> <%= Ingredient.find(dose.ingredient_id).name %> </h4>
   <p><%= link_to "Delete this dose", cocktail_dose_path(cocktail_id: @cocktail.id, id: dose.id), method: :delete %></p>
   <% end %>

<p><%= link_to "Add a dose", new_cocktail_dose_path(@cocktail) %></p>

<p><%= link_to "All the cocktails", cocktails_path %></p>

<p><%= link_to "Edit this cocktail", edit_cocktail_path(@cocktail) %></p>

<p><%= link_to "Delete this cocktail", cocktail_path(@cocktail), method: :delete %></p>

app/views/doses/new.html.erb
<%= simple_form_for [@cocktail, @dose] do |f| %>
  <%= f.input :description %>
  <%= f.association :ingredient %>
  <%= f.submit "Add a dose", class: "btn btn-primary" %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>